// This rust code generated by Google's Gemini CLI, not mine. I just throw step-by-step logic to Google's Gemini.

use std::fs;
use std::path::{Path, PathBuf};
use std::ffi::OsStr;

fn main() -> std::io::Result<()> {
    // 1. select a month folder (e.g., 04-2026)
    // We'll look for directories in the parent directory of the current executable's workspace
    // Assuming we run from the root of the project.
    let root = Path::new("../");
    let mut month_folders: Vec<PathBuf> = fs::read_dir(root)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.is_dir() && 
            path.file_name()
                .and_then(OsStr::to_str)
                .map(|s| s.contains('-') && s.split('-').all(|part| part.chars().all(char::is_numeric)))
                .unwrap_or(false)
        })
        .collect();

    // Sort by name (assuming format MM-YYYY) - though YYYY-MM would be better for sorting.
    // For now, let's just pick the latest by modification time or alphabetical.
    month_folders.sort_by(|a, b| b.file_name().cmp(&a.file_name()));
    
    let latest_month = match month_folders.first() {
        Some(path) => path,
        None => {
            println!("No month folder found.");
            return Ok(());
        }
    };
    println!("Selected month folder: {:?}", latest_month);

    // 2. find a .md file updated latest
    let mut md_files: Vec<(u32, PathBuf)> = fs::read_dir(latest_month)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(OsStr::to_str) == Some("md"))
        .filter_map(|path| {
            let stem = path.file_stem()?.to_str()?;
            if stem.ends_with("_day") {
                let num_str = stem.split('_').next()?;
                num_str.parse::<u32>().ok().map(|n| (n, path))
            } else {
                None
            }
        })
        .collect();

    md_files.sort_by(|a, b| b.0.cmp(&a.0));

    let (_latest_day, latest_file_path) = match md_files.first() {
        Some(data) => data,
        None => {
            println!("No _day.md files found in {:?}", latest_month);
            return Ok(());
        }
    };
    println!("Latest day file: {:?}", latest_file_path);

    // 3. compress the folder using multi-threading
    let output_path = latest_month.with_extension("7z");
    
    if output_path.exists() {
        println!("Archive {:?} already exists. Skipping compression.", output_path);
    } else {
        println!("Compressing {:?} to {:?}...", latest_month, output_path);
        // compress_multi_threaded(latest_month, &output_path)?;
        println!("Compression finished successfully.");
    }

    Ok(())
}
